---
apiVersion: v1
kind: Pod
metadata:
  labels:
    run: webapp
  name: webapp
spec:
  containers:
    - image: webapp-color:latest
      name: webapp
      imagePullPolicy: IfNotPresent
      ports:
        - containerPort: 8080
      args:
        - "--color"
        - "blue"
      resources:
        limits:
          memory: "128Mi"
          cpu: "500m"
  restartPolicy: Always
