---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: webapp-stateful
spec:
  selector:
    matchLabels:
      run: webapp
  serviceName: webapp
  replicas: 3
  minReadySeconds: 10
  template:
    metadata:
      labels:
        run: webapp
    spec:
      containers:
        - name: webapp
          image: webapp-color:v1
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
              protocol: TCP
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
